"""因子实现注册表：id -> meta/params/signal/flags。

负收益冒烟因子已从注册表移除（见 factors_service.RETIRED_FACTOR_IDS）。
"""
from __future__ import annotations

from typing import Any, Dict

from app.services.factors import signal_specs as sig

_COMMON = {
    "universe": "hs300",
    "price_start": "2016-01-01",
    "max_positions": 8,
    "commission_rate": 0.0001,
    "stamp_tax_sell": 0.001,
    "request_interval_sec": 0.35,
    "bench_code": "sh.000300",
}


def _p(**kwargs: Any) -> Dict[str, Any]:
    return {**_COMMON, **kwargs}


FACTOR_IMPL: Dict[str, Dict[str, Any]] = {
    "pb_low_ma_reclaim": {
        "name": "低PB回踩确认",
        "category": "fundamental",
        "description": "PB历史分位偏低时，等待收盘重新站上MA60，避免单纯抄底。",
        "tags": ["估值", "PB", "均线", "回踩"],
        "title": "Low PB + MA60 reclaim",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_pb_low_ma_reclaim,
        "params": _p(val_window=756, pb_pct_max=0.25, hold_days=20, stop_loss=0.12),
    },
    "double_cheap_reclaim": {
        "name": "双低估回踩",
        "category": "fundamental",
        "description": "PE与PB同时处在偏低分位，收盘站上MA20。",
        "tags": ["估值", "PE", "PB", "均线"],
        "title": "Double cheap PE/PB reclaim",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_double_cheap_reclaim,
        "params": _p(val_window=756, pe_pct_max=0.35, pb_pct_max=0.35, hold_days=20, stop_loss=0.12),
    },
    "growth_breakout": {
        "name": "高增突破",
        "category": "fundamental",
        "description": "业绩高增长闸门下，收盘突破60日高点且站上MA20。",
        "tags": ["成长", "突破", "均线"],
        "title": "Growth breakout",
        "need_profit": False,
        "need_growth": True,
        "signal": sig.signal_growth_breakout,
        "params": _p(growth_min=0.25, hold_days=20, stop_loss=0.15),
    },
    "oversold_roe_bounce": {
        "name": "急跌ROE反弹",
        "category": "fundamental",
        "description": "ROE质量闸门下，短期急跌后收盘站上MA20。",
        "tags": ["ROE", "超卖", "反弹"],
        "title": "Oversold ROE bounce",
        "need_profit": True,
        "need_growth": False,
        "signal": sig.signal_oversold_roe_bounce,
        "params": _p(roe_min=0.08, dd_need=0.12, hold_days=15, stop_loss=0.12),
    },
    "pead_roe_drift": {
        "name": "ROE改善漂移",
        "category": "fundamental",
        "description": "ROE改善披露后，数日内回踩MA20不破再买（简化PEAD）。",
        "tags": ["PEAD", "ROE", "财报后"],
        "title": "ROE improvement post-drift",
        "need_profit": True,
        "need_growth": False,
        "signal": sig.signal_pead_post_earn,
        "params": _p(roe_improve=0.005, pead_wait=5, hold_days=20, stop_loss=0.12),
    },
    "volume_breakout": {
        "name": "放量突破",
        "category": "technical",
        "description": "成交额明显放大且收盘突破60日高点。",
        "tags": ["放量", "突破"],
        "title": "Volume surge breakout",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_volume_breakout,
        "params": _p(vol_mult=1.8, ret20_max=0.25, hold_days=15, stop_loss=0.12),
    },
    "narrow_range_breakout": {
        "name": "窄幅突破",
        "category": "technical",
        "description": "近端振幅处在低分位后，收盘创20日新高。",
        "tags": ["波动收敛", "突破"],
        "title": "Narrow range breakout",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_narrow_range_breakout,
        "params": _p(amp_pct_max=0.25, hold_days=15, stop_loss=0.12),
    },
    "pb_below_one_reclaim": {
        "name": "破净回踩",
        "category": "fundamental",
        "description": "PB小于1时，收盘站上MA20再买。",
        "tags": ["破净", "PB", "均线"],
        "title": "PB below one reclaim",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_pb_below_one_reclaim,
        "params": _p(pb_max=1.0, hold_days=20, stop_loss=0.12),
    },
    "turn_surge_ma_reclaim": {
        "name": "换手放大上均线",
        "category": "technical",
        "description": "换手相对20日均值明显放大，同时收盘站上MA60。",
        "tags": ["换手", "资金", "均线"],
        "title": "Turnover surge MA60 reclaim",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_turn_surge_ma_reclaim,
        "params": _p(surge_ratio=2.0, hold_days=15, stop_loss=0.12),
    },
    "boll_lower_reclaim": {
        "name": "布林下轨反弹",
        "category": "technical",
        "description": "价格触及布林下轨附近后，收盘站上MA20。",
        "tags": ["布林", "超卖", "反弹"],
        "title": "Bollinger lower reclaim",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_boll_lower_reclaim,
        "params": _p(boll_window=20, boll_k=2.0, hold_days=12, stop_loss=0.10),
    },
    "new_high_pullback": {
        "name": "新高回踩",
        "category": "technical",
        "description": "创120日新高后出现回撤，再站上MA20。",
        "tags": ["新高", "回踩", "强势"],
        "title": "New high pullback",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_new_high_pullback,
        "params": _p(lookback=15, dd_need=0.04, hold_days=15, stop_loss=0.12),
    },
    "dual_ma_volume": {
        "name": "放量金叉",
        "category": "technical",
        "description": "MA20上穿MA60且成交额放大。",
        "tags": ["金叉", "放量", "趋势"],
        "title": "Dual MA cross with volume",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_dual_ma_volume,
        "params": _p(vol_mult=1.3, hold_days=20, stop_loss=0.12),
    },
    "pe_quality_cross": {
        "name": "低估值质量金叉",
        "category": "fundamental",
        "description": "PE分位偏低且ROE达标时，MA20上穿MA60。",
        "tags": ["估值", "ROE", "金叉"],
        "title": "Cheap PE quality golden cross",
        "need_profit": True,
        "need_growth": False,
        "signal": sig.signal_pe_quality_cross,
        "params": _p(val_window=756, pe_pct_max=0.50, roe_min=0.10, hold_days=25, stop_loss=0.12),
    },
    "ret20_extreme_bounce": {
        "name": "二十日急跌反弹",
        "category": "technical",
        "description": "20日跌幅过深后，收盘重新站上MA20。",
        "tags": ["超卖", "反弹", "均线"],
        "title": "20-day crash bounce",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_ret20_extreme_bounce,
        "params": _p(ret20_min=0.15, hold_days=10, stop_loss=0.10),
    },
    "amount_shrink_breakout": {
        "name": "缩量后放量突破",
        "category": "technical",
        "description": "成交额先萎缩再放量，同时收盘突破20日高点。",
        "tags": ["缩量", "放量", "突破"],
        "title": "Shrink-then-surge breakout",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_amount_shrink_breakout,
        "params": _p(shrink_ratio=0.6, surge_ratio=1.5, hold_days=12, stop_loss=0.12),
    },
    "bottom_earn_vol_break": {
        "name": "底部业绩放量突破",
        "category": "fundamental",
        "description": (
            "长期磨底且估值不高，业绩由弱转强（扭亏/同比改善）后，"
            "缩量蓄势再放量突破；对齐仕佳光子类路径。"
        ),
        "tags": ["长期底部", "业绩扭亏", "放量", "突破"],
        "title": "LT bottom + earnings turnaround + volume breakout",
        "need_profit": True,
        "need_growth": True,
        "signal": sig.signal_bottom_earn_vol_break,
        "params": _p(
            val_window=756,
            near_low_pct=0.12,
            near_zone_pct=0.45,
            dd_252_need=0.28,
            bottom_lookback=252,
            max_lift_from_low=0.55,
            pb_pct_max=0.50,
            pe_pct_max=0.55,
            val_lookback=60,
            funda_hist=400,
            roe_weak_max=0.02,
            roe_min=0.0,
            roe_improve=0.003,
            earn_window=180,
            growth_min=0.10,
            growth_lift=0.20,
            quiet_ratio=0.95,
            vol_mult=1.7,
            vol_lag=5,
            ret20_max=0.25,
            ret60_max=0.60,
            cooldown_days=20,
            hold_days=40,
            stop_loss=0.15,
        ),
    },
    "crash_long_base_break": {
        "name": "大跌长横盘突破",
        "category": "technical",
        "description": (
            "两年维度大跌后进入长箱体横盘，估值不高，"
            "缩量蓄势后放量突破近端箱顶；强调「磨得够久」再突破。"
        ),
        "tags": ["大跌", "横盘", "箱体", "放量突破", "估值"],
        "title": "Crash + long base + volume breakout",
        "need_profit": False,
        "need_growth": False,
        "signal": sig.signal_crash_long_base_break,
        "params": _p(
            val_window=756,
            crash_dd=0.38,
            crash_lookback=400,
            off_peak_dd=0.18,
            base_range_max=0.55,
            vol_pct_max=0.55,
            lift_from_low_min=0.02,
            lift_from_low_max=0.60,
            base_age_min=90,
            old_touch_win=252,
            trough_near=0.05,
            break_lookback=60,
            quiet_ratio=0.95,
            vol_mult=1.6,
            vol_lag=5,
            ret20_max=0.22,
            pb_pct_max=0.55,
            pe_pct_max=0.60,
            val_lookback=60,
            cooldown_days=25,
            hold_days=35,
            stop_loss=0.14,
        ),
    },
    "crash_base_earn_break": {
        "name": "长横盘业绩确认突破",
        "category": "fundamental",
        "description": (
            "大跌长横盘基础上，要求业绩由弱转强（ROE/同比），"
            "再放量突破；用基本面过滤假突破。"
        ),
        "tags": ["大跌", "横盘", "业绩转好", "放量突破"],
        "title": "Long base + earnings turn + breakout",
        "need_profit": True,
        "need_growth": True,
        "signal": sig.signal_crash_base_earn_break,
        "params": _p(
            val_window=756,
            crash_dd=0.40,
            crash_lookback=400,
            off_peak_dd=0.22,
            base_range_max=0.52,
            vol_pct_max=0.50,
            lift_from_low_min=0.02,
            lift_from_low_max=0.60,
            base_age_min=150,
            old_touch_win=300,
            trough_near=0.05,
            break_lookback=60,
            quiet_ratio=0.95,
            vol_mult=1.5,
            vol_lag=5,
            ret20_max=0.25,
            pb_pct_max=0.65,
            pe_pct_max=0.70,
            val_lookback=60,
            funda_hist=400,
            roe_weak_max=0.03,
            roe_min=0.0,
            roe_improve=0.003,
            earn_window=180,
            growth_min=0.05,
            growth_lift=0.15,
            cooldown_days=25,
            hold_days=40,
            stop_loss=0.15,
        ),
    },
}


def compute_factor_signal(factor_id: str, params: Dict[str, Any] | None = None, asof: str | None = None):
    from app.services.factors.runner import latest_candidates

    meta = FACTOR_IMPL[factor_id]
    p = {**meta["params"], **(params or {})}
    return latest_candidates(
        factor_id,
        meta["signal"],
        p,
        need_profit=meta["need_profit"],
        need_growth=meta["need_growth"],
        asof=asof,
    )
